scrape_configs:
  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'

  # Redis Exporter 메트릭
  - job_name: 'redis-exporter'
    static_configs:
      - targets:
          - 'redis-exporter:9121'

  # Spring Boot 애플리케이션
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
