name: Build Spring Boot with Gradle and Push Docker Image

on:
  push:
    branches:
      - deploy  # main 브랜치로 푸시될 때 트리거

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 환경 설정
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gradle 빌드 (Spring Boot JAR 생성)
      - name: Build with Gradle
        run: |
            echo "gradle 빌드 시작"
            chmod +x ./gradlew./gradlew build
            echo "gradle 빌드 완료"

      # 4. Docker 설치 확인
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 5. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:latest .

      # 7. Docker 이미지 푸시
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:latest